name: intercom_platform_interface
description: A common platform interface for the intercom_flutter_plugin.
version: 1.0.1
issue_tracker: https://github.com/chuvakpavel/IntercomeFlutter/issues
repository: https://github.com/chuvakpavel/IntercomeFlutter/tree/main/intercom_platform_interface

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=3.0.0 <4.0.0'