name: intercom_ios
description: iOS implementation of the intercom_flutter_plugin.
repository: https://github.com/chuvakpavel/IntercomeFlutter/tree/main/intercom_ios
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  intercom_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  pigeon: ^10.1.3

flutter:
  plugin:
    implements: intercom_flutter_plugin
    platforms:
      ios:
        dartPluginClass: IosIntercom
        pluginClass: IntercomIosPlugin
